### ISSUE TITLE
Fix bug clubs pages

### ISSUE THREAD

**Issue by songpham** [songpham/CfycDesigner#10]
Hi Manh, here is your links, please download it, before starting your amazing work:

_Instruction:_
- Put club description underneath headline above slideshow
- No descriptions / text in slideshow
- Currently cfyc clubs page: http://www.cfyc.com.vn/cau-lac-bo-tai-ho-chi-minh-pa3lo1lg2.html
- My goal is creating clubs pages for all of the cities that have cfyc clubs (hcm, hanoi...)
- Url should be: club-hcm, club-hanoi, club-da-nang
- When click to club, scroll to the info of the club (gallery, slideshow, location...). The information should get from our current cfyc website
- Each club, should have at least 4 thumbnail images.

_Pages_
- PTS file: http://www.mediafire.com/download/nd5r6gi33f49o38/cfyc_clubs_hcm.psd

Thank you, hope you well-done!!!

**Comment by dinhthaimanh** [comment]
done
