### ISSUE TITLE
Home Page Update 10 August:

### ISSUE THREAD

**Issue by GlenCoffey** [songpham/CfycDesigner#22]
<img width="706" alt="screen shot 2015-08-10 at 12 09 28" src="https://cloud.githubusercontent.com/assets/13463750/9159744/bf8cfa26-3f58-11e5-9c3f-16dac82a79da.png">
Home page is OK but these need to be updated ASAP. The link again is:

http://www.mediafire.com/download/h0e3yjp4mtxh181/Home_Page_PTs.zip

After you have changed the images, please wait for review from our Brand Manager. 

Thanks Bod!

**Comment by boducoscar** [comment]
done
