### ISSUE TITLE
Member Testimonials Banner Change

### ISSUE THREAD

**Issue by GlenCoffey** [songpham/CfycDesigner#5]
The design has been updated. 
The button in the banner "Get A Trial" should link to # it will link to a VIP tour page. 
Please ensure your page is up to date with the design. 

If you're assigned this and you havent created the page, please let me know ASAP.

**Comment by GlenCoffey** [comment]
New design: https://drive.google.com/file/d/0BxaLYxD1wR7AUFJ2S29iVERZVm8/view

**Comment by boducoscar** [comment]
done

**Comment by dinhthaimanh** [comment]
updated !
